#!/usr/bin/env bash
# A script that transfers a file from our client to a server using scp.

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Command line arguments
file_path=$1
server_ip=$2
server_username=$3
ssh_key_path=$4

# To transfer file to server using scp
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$server_username@$server_ip":~
