#!/usr/bin/env bash
# Install Nginx web server
# Update package list
# Install Nginx
# Create a file containing "Hello World!"

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx start