#!/usr/bin/env bash
# Install Nginx web server

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Start Nginx
sudo service nginx start

# Create a file containing "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
