#!/usr/bin/env bash
# Install Nginx
#
# Allow incoming traffic on port 80
#
# Configure Nginx to listen on port 80
# and return "Hello World!"
#
# Configure redirection from /redirect_me to a specified URL
#
# Restart Nginx
#

sudo apt-get update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
echo "server {
        listen 80;
        location /redirect_me {
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}" > /etc/nginx/sites-available/default
service nginx restart
