#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx to use custom 404 page
new_conf="server_name _;\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t\troot /var/www/html;\n\t}"
sed -i "s/server_name _;/$new_conf/" /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
