#!/usr/bin/env bash
# Update and Install Nginx package list
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom 404 page containing the required string
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Modify the Nginx default configuration file to redirect 404 errors to the custom page
sudo sed -i '/listen \[::\]:80 default_server;/a \\n\t# Redirect 404 errors to custom 404 page\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
