#!/usr/bin/env bash

# Install HAproxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAproxy
sudo sed -i 's/^\(.*\)frontend\ \(.*\)$/\1frontend \2\n    bind \*:80\n    mode http\n    default_backend web-backend/' /etc/haproxy/haproxy.cfg
sudo sh -c "echo 'backend web-backend\n    mode http\n    balance roundrobin\n    server web-01 52.3.247.44:80 check\n    server web-02 54.197.105.43:80 check' >> /etc/haproxy/haproxy.cfg"

# Enable HAproxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAproxy
sudo service haproxy restart
