#!/usr/bin/env bash

# Update and upgrade packages
sudo apt-get update
sudo apt-get upgrade -y

# Install HAproxy
sudo apt-get install -y haproxy

# Configure HAproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

sudo cat <<EOF > /etc/haproxy/haproxy.cfg
frontend lb-frontend
    bind *:80
    mode http
    default_backend lb-backend

backend lb-backend
    mode http
    balance roundrobin
    server web-01 54.224.21.248:80 check
    server web-02 100.25.28.51:80 check
EOF

# Restart HAproxy
sudo service haproxy restart

# HAproxy to starts automatically on boot
sudo update-rc.d haproxy defaults
