#!/usr/bin/env bash

# This script configures it to listen on port 80 of all active IPv4 IPs

# Start Nginx service
sudo service nginx start

# Change Nginx configuration to listen on port 80 of all active IPv4 IPs
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
