#!/usr/bin/env bash
# This script installs Nginx and configures it to listen on port 80 of all active IPv4 IPs

# Change Nginx configuration to listen on port 80 of all active IPv4 IPs
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default

# Start Nginx service
service nginx start
